---
title: "Data_Cleaning"
author: "Anh Vo"
date: "2023-04-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(broom)
library(lubridate)
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
library("syuzhet")
library("ggplot2")
```

```{r}
library(dplyr)
library(readxl)
aba_data <- read.csv("/Users/anh.vo/Downloads/datafest2023/data/datasetABA.csv") 
```


```{r get population}
aba_data$Year <- year(as.POSIXlt(aba_data$ClosedOnUtc, format="%Y-%m-%d %H:%M:%S", tz="UTC"))
sen <- subset(aba_data, select = c(Category, Subcategory, Conversation))
```

```{r}
demo <- aba_data %>%
  select(Category, Subcategory, Conversation) %>%
  group_by(Category, Subcategory) %>%
  summarize(num = n()) %>%
  ungroup() %>%
  group_by(Category) %>%
  mutate(rank = dense_rank(desc(num))) %>%
  group_by(Category, rank) %>%
  mutate(Subcategory = if_else(rank <= 5, Subcategory, "The Rest")) %>%
  group_by(Category, Subcategory) %>%
  summarize(num = sum(num)) %>%
  ungroup() %>%
  arrange(Category, desc(num))

```

```{r}
colors <- ifelse(consumer$Subcategory == "The Rest", "white", c("#08306b", "#08519c", "#2171b5", "#4292c6", "#6baed6"))

consumer <- demo %>%
  filter(Category == "Consumer Financial Questions")
edu <- demo %>%
  filter(Category == "Education")
family <- demo %>%
  filter(Category == "Family and Children")
health <- demo %>%
  filter(Category == "Health and Disability")
housing <- demo %>%
  filter(Category == "Housing and Homelessness")
income <- demo %>%
  filter(Category == "Income Maintenance")
rights <- demo %>%
  filter(Category == "Individual Rights")
juvenile <- demo %>%
  filter(Category == "Juvenile")
other <- demo %>%
  filter(Category == "Other")
work <- demo %>%
  filter(Category == "Work, Employment and Unemployment")
```

```{r}
pie(consumer$num, labels = consumer$Subcategory, main = "Consumer Financial Questions", col =  ifelse(consumer$Subcategory == "The Rest", "white", c("#08306b", "#08519c", "#2171b5", "#4292c6", "#6baed6", "#3590e6")))
pie(edu$num, labels = edu$Subcategory, main = "Education", col =  ifelse(edu$Subcategory == "The Rest", "white", c("#08306b", "#08519c", "#2171b5", "#4292c6", "#6baed6", "#3590e6")))
pie(family$num, labels = family$Subcategory, main = "Family and Children", col =  ifelse(family$Subcategory == "The Rest", "white", c("#08306b", "#08519c", "#2171b5", "#4292c6", "#6baed6", "#3590e6")))
pie(health$num, labels = health$Subcategory, main = "Health and Disability", col =  ifelse(health$Subcategory == "The Rest", "white", c("#08306b", "#08519c", "#2171b5", "#4292c6", "#6baed6", "#3590e6")))
pie(housing$num, labels = housing$Subcategory, main = " Housing and Homelessness",col =  ifelse(housing$Subcategory == "The Rest", "white", c("#08306b", "#08519c", "#2171b5", "#4292c6", "#6baed6", "#3590e6")))
pie(income$num, labels = income$Subcategory, main = "Income Maintenance",col =  ifelse(income$Subcategory == "The Rest", "white", c("#08306b", "#08519c", "#2171b5", "#4292c6", "#6baed6", "#3590e6")))
pie(rights$num, labels = rights$Subcategory,main = "Individual Rights", col =  ifelse(rights$Subcategory == "The Rest", "white", c("#08306b", "#08519c", "#2171b5", "#4292c6", "#6baed6", "#3590e6")))
pie(juvenile$num, labels = juvenile$Subcategory, main = "Juvenile",col =  ifelse(juvenile$Subcategory == "The Rest", "white", c("#08306b", "#08519c", "#2171b5", "#4292c6", "#6baed6", "#3590e6")))
pie(other$num, labels = other$Subcategory, main = "Other",col =  ifelse(other$Subcategory == "The Rest", "white", c("#08306b", "#08519c", "#2171b5", "#4292c6", "#6baed6", "#3590e6")))
pie(work$num, labels = work$Subcategory, main = "Work, Employment and Unemployment",col =  ifelse(work$Subcategory == "The Rest", "white", c("#08306b", "#08519c", "#2171b5", "#4292c6", "#6baed6", "#3590e6")))
```

```{r}
set.seed(04162023)

temp_con <- sen %>%
  filter(Category == "Consumer Financial Questions",
         Subcategory == "Debts & Purchases")
temp_con <- temp_con[sample(nrow(temp_con), 4000), ]

temp_edu <- sen %>%
  filter(Category == "Education")

temp_fam <- sen %>%
  filter(Category == "Family and Children",
         Subcategory == "Family/Divorce/Custody") 
temp_fam <- temp_fam[sample(nrow(temp_fam), 4000), ]

temp_health <- sen %>%
  filter(Category == "Health and Disability")
temp_health <- temp_health[sample(nrow(temp_health), 4000), ]

temp_house <- sen %>%
  filter(Category == "Housing and Homelessness",
         Subcategory == "Housing or Property Owned") 
temp_house <- temp_house[sample(nrow(temp_house), 4000), ]

temp_income <- sen %>%
  filter(Category == "Income Maintenance")
temp_income <- temp_income[sample(nrow(temp_income), 4000), ]

temp_rights <- sen %>%
  filter(Category == "Individual Rights",
         Subcategory == "Civil/Constitutional Rights") 
temp_rights <- temp_rights[sample(nrow(temp_rights), 4000), ]

temp_juv <- sen %>%
  filter(Category == "Juvenile")

temp_other <- sen %>%
  filter(Category == "Other",
         Subcategory == "Other") 
temp_other <- temp_other[sample(nrow(temp_other), 4000), ]

temp_work <- sen %>%
  filter(Category == "Work, Employment and Unemployment",
         Subcategory == "Work") 
temp_work <- temp_work[sample(nrow(temp_work), 4000), ]


```

```{r}
cloud <- function(sourceText) {
  
TextDoc <- Corpus(VectorSource(sourceText))

 #Replacing "/", "@" and "|" with space
toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
TextDoc <- tm_map(TextDoc, toSpace, "/")
TextDoc <- tm_map(TextDoc, toSpace, "@")
TextDoc <- tm_map(TextDoc, toSpace, "\\|")
# Convert the text to lower case
TextDoc <- tm_map(TextDoc, content_transformer(tolower))
# Remove numbers
TextDoc <- tm_map(TextDoc, removeNumbers)
# Remove english common stopwords
TextDoc <- tm_map(TextDoc, removeWords, stopwords("english"))
# Remove your own stop word
# specify your custom stopwords as a character vector
TextDoc <- tm_map(TextDoc, removeWords, c("s", "company", "team")) 
# Remove punctuations
TextDoc <- tm_map(TextDoc, removePunctuation)
# Eliminate extra white spaces
TextDoc <- tm_map(TextDoc, stripWhitespace)
# Text stemming - which reduces words to their root form
TextDoc <- tm_map(TextDoc, stemDocument)
TextDoc <- tm_map(TextDoc, removeWords, c("can", "will"))

TextDoc_dtm <- TermDocumentMatrix(TextDoc)
dtm_m <- as.matrix(TextDoc_dtm)
# Sort by descearing value of frequency
dtm_v <- sort(rowSums(dtm_m),decreasing=TRUE)
dtm_d <- data.frame(word = names(dtm_v),freq=dtm_v)

return (dtm_d)
}
```

```{r}
cat1 <- cloud(temp_con$Conversation)
cat2 <- cloud(temp_edu$Conversation)
cat3 <- cloud(temp_fam$Conversation)
cat4 <- cloud(temp_health$Conversation)
cat5 <- cloud(temp_house$Conversation)
cat6 <- cloud(temp_income$Conversation)
cat7 <- cloud(temp_rights$Conversation)
cat8 <- cloud(temp_juv$Conversation)
cat9 <- cloud(temp_other$Conversation)
cat10 <- cloud(temp_work$Conversation)
```


```{r}
d <- get_nrc_sentiment(temp_con$Conversation)
head (d,10)
```

```{r}
d <- get_nrc_sentiment(temp_edu$Conversation)
head (d,10)
```

```{r}
d <- get_nrc_sentiment(temp_fam$Conversation)
head (d,10)
```

```{r}
d <- get_nrc_sentiment(temp_house$Conversation)
head (d,10)
```

```{r}
d <- get_nrc_sentiment(temp_health$Conversation)
head (d,10)
```

```{r}
d <- get_nrc_sentiment(temp_house$Conversation)
head (d,10)
```

```{r}
d <- get_nrc_sentiment(temp_income$Conversation)
head (d,10)
```

```{r}
d <- get_nrc_sentiment(temp_rights$Conversation)
head (d,10)
```

```{r}
d <- get_nrc_sentiment(temp_juv$Conversation)
head (d,10)
```

```{r}
d <- get_nrc_sentiment(temp_work$Conversation)
head (d,10)
```

### Get sentiment graphs

```{r}
#transpose
td<-data.frame(t(d))
#The function rowSums computes column sums across rows for each level of a grouping variable.
td_new <- data.frame(rowSums(td[1:549]))
#Transformation and cleaning
names(td_new)[1] <- "count"
td_new <- cbind("sentiment" = rownames(td_new), td_new)
rownames(td_new) <- NULL
td_new2<-td_new[1:8,]
#Plot One - count of words associated with each sentiment
library(ggplot2)

my_colors <- c("#08306b", "#08519c", "#2171b5", "#4292c6", "#6baed6", "#9ecae1", "#c6dbef", "#3590e6")

# Create the plot and specify the color palette
my_plot <- ggplot(td_new2, aes(x = sentiment, y = count, fill = sentiment)) + 
  geom_bar(stat = "identity") + 
  scale_fill_manual(values = my_colors) +
  labs(x = NULL, y = "Count", title = "Juvenile")
my_plot
```

```{r}
ggsave("plot_juv.png", my_plot, width = 8, height = 5, dpi = 300)
```

```{r}
rm(temp_juv, temp_other, td, d, td_new, td_new2)
```


```{}
# Load the required package

# Set the size of the plotting area and the background color
png(width = 800, height = 600, bg = "black", filename = "Housing.png")

# Generate the word cloud with a blue color palette
wordcloud(words = cat5$word, freq = cat5$freq, min.freq = 5,
          max.words = 200, random.order = FALSE, rot.per = 0.40, 
          colors = brewer.pal(9, "Blues"), 
          scale = c(4, 0.5)) # adjust the size of the words

# Save the word cloud to a file
dev.off()
```




```{r}
attorney <- read.csv("/Users/anh.vo/Downloads/datafest2023/data/attorney_full.csv") 
```


```{r}
att <- attorney %>%
  group_by(AttorneyUno) %>%
  summarize(avg_hour = round(mean(Hours, na.rm=T),2))
```

```{r}
aba_data$Year <- year(as.POSIXlt(aba_data$ClosedOnUtc, format="%Y-%m-%d %H:%M:%S", tz="UTC"))

aba <- aba_data %>%
  select(c(StateAbbr, Category, Subcategory, TakenByAttorneyUno, Year))
```

```{r}
temp <- left_join(aba, att, by = c("TakenByAttorneyUno" = "AttorneyUno"))
```


```{r}
library(lubridate)
library(ggthemes)
p <- ggplot(data = temp2) +
geom_line(aes(x = Year, y = avg_hour, color = Category)) +
labs(x = "Year", y = "Average Attorney Response Hours") +
ggtitle("Response Rate by Category",
subtitle = "2016 to 2022") +
theme_economist() +
theme(plot.title = element_text(hjust =0.5),
plot.subtitle = element_text(hjust =0.5))
```
```{r}
ggsave("response_hour.png", p, width = 14, height = 5, dpi = 300)
```





```{r}
temp2 <- temp %>%
  group_by(Category, Year) %>%
  summarize(avg_hour = round(mean(avg_hour, na.rm=T),2))

```





